# Site settings
title: Rowan Meara
email: rowanmeara@gmail.com
url: http://rowanmeara.com
description: "Personal website of Rowan Meara."
keywords: "Rowan, Rowan Meara, Software Engineer, Portfolio, Esports, SQL, Python, C, JavaScript"
skills: "Software Engineer -- Seattle"
meta_author: Meara Rowan
about: "I’m a recent computer science graduate from Cornell University with a passion for back-end development and performative code and applications. While in college, I worked as an intern at IceCube and a teaching assistant for Operating Systems. Recently, I created EsportsTracker.net."
# Google webmaster tools
google_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  304FFE
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 1A237E #FD6E8A
  secondary-dark: 233140 #1A237E

# Footer settings
footer:
  copyright: Rowan Meara
  location: Seattle
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/RowanMeara
  - title: linkedin
    url: https://linkedin.com/in/RowanMeara

# Postal address (add as many lines as necessary)
address:
  - line: rowanmeara@gmail.com
  - line: 1726 NW 64th St
  - line: Seattle, WA 98107

# Build settings
markdown: kramdown
permalink: pretty
